# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luke Hackett
url: "http://www.lukehackett.com"

# Site Author
about:
  author: Luke Hackett
  job: Software Developer
  gravatar: "http://1.gravatar.com/avatar/5063276d68503fad5da5aa860438ca83?size=150"
  description: |
      Luke is a full stack developer, amateur photographer, a reader of many
      subjects, and a global traveller who occasionally blogs about some of 
      his interests and discoveries.

# Site Navigation
navigation:
  - label: Posts
    url: /
  - label: Archive
    url: /archive/
  - label: Projects
    url: /projects/
  - label: Travel
    url: /travel/
  - label: About
    url: /about/

# Pagination
paginate: 5
paginate_path: '/posts/:num/'

# Site Collections
collections:
  posts:
    output: true
    permalink: /posts/:title
  projects:
    output: true
    permalink: /projects/:title

# Excerpt separator
excerpt_separator: <!--excerpt-->

# Social
social:
  atom:
    label: Atom
    url: "/atom.xml"
  rss:
    label: RSS
    url: "/rss.xml"
  twitter:
    label: Twitter
    url: "https://twitter.com/luke_hackett"
  linkedin:
    label: LinkedIn
    url: "https://uk.linkedin.com/pub/luke-hackett/82/561/423"
  github:
    label: GitHub
    url: "https://github.com/LukeHackett"

# Atom feed
feed:
  path: atom.xml

# Site footer
footer:
  copyright: "&copy; 2020 Luke Hackett."

# Discuss
disqus: 
  embed: "https://lukehackettcom.disqus.com/embed.js"
  count: "//lukehackettcom.disqus.com/count.js"

# Google Analytics
google_analytics: UA-156066646-1

# Build settings
markdown: kramdown

# Jekyll plugins
plugins:
  - jekyll-tidy
  - jekyll-feed
  - jekyll-paginate

# sass settings
sass:
  sass_dir: _sass
  style: compressed
