# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luke Hackett
tagline: Yet another opinionated software engineering blog
author: Luke Hackett
description: >
  Another opinionated software engineering blog written by a full stack
  developer living in West London, United Kingdom. I create extensible,
  functional, simple software solutions to a variety of problems, and
  occasionally blog about my interests.
url: "http://www.lukehackett.com"
discuss: 
  embed: "https://lukehackettcom.disqus.com/embed.js"
  count: "//lukehackettcom.disqus.com/count.js"

# social networks
linkedin: "https://uk.linkedin.com/pub/luke-hackett/82/561/423"
twitter:  "https://twitter.com/luke_hackett"
github:   "https://github.com/LukeHackett"
gravatar: "http://1.gravatar.com/avatar/5063276d68503fad5da5aa860438ca83?size=200"

# Build settings
markdown: kramdown

# sass settings
sass:
  sass_dir: _sass
  style: compressed

# Google Analytics
google_analytics: UA-89802036-2
